# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"  # Title of the link.
  url = "about/"  # Widget Page folder name.
  weight = 10  # Position of the link in the navigation bar.

[[main]]
  name = "Research"  # Title of the link.
  url = "personal/"  # Widget Page folder name.
  weight = 20  # Position of the link in the navigation bar.

[[main]]
  name = "Teaching"  # Title of the link.
  url = "teaching/"  # Widget Page folder name.
  weight = 30  # Position of the link in the navigation bar.

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 40

#[[main]]
#  name = "Reading"  # Title of the link.
#  url = "reading/"  # Widget Page folder name.
#  weight = 2  # Position of the link in the navigation bar.

#[[main]]
#  name = "Demo"
#  url = "#hero"
#  weight = 10

#[[main]]
#  name = "Posts"
#  url = "post/"
#  weight = 20

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#[[main]]
#  name = "Resources"
#  url = "resources/"
#  weight = 50


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
